# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0003_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
    ]
