# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0004_reservation_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingrestaurant',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restorani.Guest'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
