# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0005_auto_20170623_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='guest',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
