# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0006_auto_20170623_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='tableNo',
            field=models.IntegerField(null=True),
        ),
    ]
