# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0007_auto_20170627_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ManyToManyField(to='restorani.Food'),
        ),
    ]
