# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restorani', '0008_auto_20170628_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('beaverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Beaverage')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Food')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='beaverages',
        ),
        migrations.RemoveField(
            model_name='order',
            name='foods',
        ),
        migrations.AddField(
            model_name='order',
            name='ordereddrinks',
            field=models.ManyToManyField(to='restorani.OrderedDrink'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderedfoods',
            field=models.ManyToManyField(to='restorani.OrderedFood'),
        ),
    ]
