# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beaverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=40)),
                ('firstLogin', models.BooleanField()),
                ('shoeSize', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=40)),
                ('activated', models.BooleanField()),
                ('address', models.CharField(max_length=250)),
                ('friends', models.ManyToManyField(to='restorani.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField()),
                ('beaverages', models.ManyToManyField(to='restorani.Beaverage')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('foods', models.ManyToManyField(to='restorani.Food')),
            ],
        ),
        migrations.CreateModel(
            name='RatingRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('complete', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('sizeX', models.IntegerField()),
                ('sizeY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=40)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairNo', models.IntegerField()),
                ('posX', models.IntegerField()),
                ('posY', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=40)),
                ('posts', models.ManyToManyField(to='restorani.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SystemManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restorani.Employee')),
            ],
            bases=('restorani.employee',),
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restorani.Employee')),
                ('kind', models.CharField(max_length=80)),
            ],
            bases=('restorani.employee',),
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restorani.Employee')),
            ],
            bases=('restorani.employee',),
        ),
        migrations.AddField(
            model_name='schedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Employee'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Segment'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Segment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='restaurantTables',
            field=models.ManyToManyField(to='restorani.RestaurantTable'),
        ),
        migrations.AddField(
            model_name='ratingservices',
            name='employees',
            field=models.ManyToManyField(to='restorani.Employee'),
        ),
        migrations.AddField(
            model_name='ratingrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
        migrations.AddField(
            model_name='post',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='employees',
            field=models.ManyToManyField(to='restorani.Employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='foods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.RestaurantTable'),
        ),
        migrations.AddField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Post'),
        ),
        migrations.AddField(
            model_name='offer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Supplier'),
        ),
        migrations.AddField(
            model_name='guest',
            name='reservations',
            field=models.ManyToManyField(to='restorani.Reservation'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
        migrations.AddField(
            model_name='beaverage',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restorani.Restaurant'),
        ),
    ]
